# Site settings
title: Dueling Monkeys
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.duelingmonkeys.com" # the base hostname & protocol for your site
comments: true
plugins_dir: _plugins

# Build settings
markdown: kramdown

exclude: ['.ruby-version', 'Gemfile', 'Gemfile.lock', 'Gemfile.lock.backup', 'Dockerfile', 'docker-compose.yml', 'provision.sh', 'README.md', 'vendor']

collections:
  games:
    output: true
  recipes:
    output: true

defaults:
  -
    scope:
      type: "posts"
    values:
      nav: "blog"
      layout: "news"
      comments: true
  -
    scope:
      type: "games"
    values:
      layout: "game"
      nav: "games"
  -
    scope:
      type: "recipes"
    values:
      layout: "recipe"
