# Site settings
title: Dueling Monkeys
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.duelingmonkeys.com" # the base hostname & protocol for your site

plugins: _plugins

# Build settings
markdown: kramdown

exclude: ['bower.json', 'Vagrantfile', 'provision.sh', 'README.md']

collections:
  games:
    output: true
  recipes:
    output: true

defaults:
  -
    scope:
      type: "post"
    values:
      nav: "blog"
  -
    scope:
      type: "games"
    values:
      layout: "game"
      nav: "games"
  -
    scope:
      type: "recipes"
    values:
      layout: "recipe"